### DISCUSSION TITLE
Features, Breaking Changes & Deprecation

### DISCUSSION THREAD

**Discussion by ful1e5** [ful1e5/clickgen#59] [Announcements]
Subscribe to this discussion to receive updates on breaking changes and deprecations.

**Comment by ful1e5** [comment]
## Changelog-08172023

**Date: August 17,  2023**
**Ref:**  8d2b722e32dc48319f30f5823809535aae36355d

In the configuration file, the `[config]` section no longer supports the 'win_size' and 'x11_sizes' options. Instead, utilize the 'win_sizes' and 'x11_sizes' settings within each cursor's configuration.


Alternatively, you can assign them to `[cursors.fallback_settings]`.

Here's the updated configuration:

```diff
# Deprecated - Avoid using these settings
[config]
# ...
- x11_sizes = [21, 24, 28, 32, 40, 48, 56, 64, 72, 80, 88, 96]
- win_size = 32

[cursors]

# Use this as the fallback for cursor sizes
[cursors.fallback_settings]
# ...
+ x11_sizes = [21, 24, 28, 32, 40, 48, 56, 64, 72, 80, 88, 96]
+ win_sizes = [32, 48]

[cursors.fake_pointer]
# ...
+ x11_sizes = [28, 32, 88, 96] # Adjust sizes for XCursors and...
+ win_sizes = [20] # ...Windows Cursors for this specific cursor
```

**Comment by ful1e5** [comment]
## Changelog-05212024

**Date: May 21, 2024**
**Ref:** 0f6e9b81327f4e2ead4d118b53791bd16918b4b2 706fbbe716fbed225414d4d1ad8613441a766ce7

Clickgen now allows cursor bitmap re-canvasing by specifying sizes using the `cursor_size:canvas_size` format.

#### Caveats

-   To utilize canvasing in config files, all sizes must be passed in `List[string]` format in both config files and Python code.

#### Using the library:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from clickgen.parser import open_blob


if __name__ == "__main__":
    # ...

    open_blob(pngs, hotspot=(100, 100), sizes=["24:32", "32"])  # ✅ Correct [CANVASING]
    open_blob(pngs, hotspot=(100, 100), sizes=["24", "32"])     # ✅ Correct [NORMAL]
    open_blob(pngs, hotspot=(100, 100), sizes=[24, 32])         # ✅ Correct [NORMAL]

    open_blob(pngs, hotspot=(100, 100), sizes=["24", 32])       # ❌ Error [NORMAL]
    open_blob(pngs, hotspot=(100, 100), sizes=["24:32", 32])    # ❌ Error [CANVASING]

```

#### Using the clickgen CLI:

```bash
clickgen samples/pngs/pointer.png -x 10 -y 10 -s "22:32" "24" "32" -p x11   # ✅ Correct [CANVASING]
clickgen samples/pngs/pointer.png -x 10 -y 10 -s "22" "24" "32" -p x11      # ✅ Correct [NORMAL]
clickgen samples/pngs/pointer.png -x 10 -y 10 -s 22 24 32 -p x11            # ✅ Correct [NORMAL]

clickgen samples/pngs/pointer.png -x 10 -y 10 -s "22" 24 32 -p x11          # ✅ Correct [NORMAL]
clickgen samples/pngs/pointer.png -x 10 -y 10 -s "22:32" 24 32 -p x11       # ✅ Correct [CANVASING]
```

#### Using the ctgen CLI:

```bash
ctgen samples/sample.toml -s "22:32" "24" "32" -p x11   # ✅ Correct [CANVASING]
ctgen samples/sample.toml -s "22" "24" "32" -p x11      # ✅ Correct [NORMAL]
ctgen samples/sample.toml -s 22 24 32 -p x11            # ✅ Correct [NORMAL]

ctgen samples/sample.toml -s "22" 24 32 -p x11          # ✅ Correct [NORMAL]
ctgen samples/sample.toml -s "22:32" 24 32 -p x11       # ✅ Correct [CANVASING]
```

#### Using the config files

##### TOML config

```toml
# ...

[cursors]
[cursors.fallback_settings]
x11_sizes = [16, 20, 24, 28, 32, 40, 48, 56, 64, 72, 80, 88, 96]

win_sizes = ['24:32', '32', '48', '64', '96']         # ✅ Correct [CANVASING]
win_sizes = ['24', '32', '48', '64', '96']            # ✅ Correct [NORMAL]
win_sizes = [24, 32, 48, 64, 96]                      # ✅ Correct [NORMAL]

win_sizes = ['24', 32, 48, 64, 96]                    # ❌ Error [NORMAL]
win_sizes = ['24:32', 32, 48, 64, 96]                 # ❌ Error [CANVASING]

[cursors.pointer1]
png = 'pointer.png'
win_name = 'Default'
x11_name = 'pointer1'
x11_symlinks = ['link1']
x11_sizes = [24, 32]

# ...
```

##### JSON config

```json5
{
    // ...

    "cursors": {
        "fallback_settings": {
            "x11_sizes": [16, 20, 24, 28, 32, 40, 48, 56, 64, 72, 80, 88, 96],
            "win_sizes": ["24:32", "32", "48", "64", "96"]         // ✅ Correct [CANVASING]
            "win_sizes": ["24", "32", "48", "64", "96"],           // ✅ Correct [NORMAL]
            "win_sizes": [24, 32, 48, 64, 96],                     // ✅ Correct [NORMAL]

            "win_sizes": ["24", 32, 48, 64, 96],                   // ❌ Error [NORMAL]
            "win_sizes": ["24:32", 32, 48, 64, 96]                 // ❌ Error [CANVASING]
        },
        "pointer1": {
            "png": "pointer.png",
            "win_name": "Default",
            "x11_name": "pointer1",
            "x11_symlinks": ["link1"],
            "x11_sizes": [24, 32]
        }

        // ...
    },
}
```

##### YAML config

```yaml
# ...

cursors:
  fallback_settings:
    x11_sizes: [16, 20, 24, 28, 32, 40, 48, 56, 64, 72, 80, 88, 96]

    win_sizes: ['24:32', '32', '48', '64', '96']         # ✅ Correct [CANVASING]
    win_sizes: ['24', '32', '48', '64', '96']            # ✅ Correct [NORMAL]
    win_sizes: [24, 32, 48, 64, 96]                      # ✅ Correct [NORMAL]

    win_sizes: ['24', 32, 48, 64, 96]                    # ❌ Error [NORMAL]
    win_sizes: ['24:32', 32, 48, 64, 96]                 # ❌ Error [CANVASING]

  pointer1:
    png: 'pointer.png'
    win_name: 'Default'
    x11_name: 'pointer1'
    x11_symlinks: ['link1']
    x11_sizes: [24, 32]

  # ...
```
